// Generated by scripts/build-states-data.py
import type { CountyDemographics } from "@/lib/states"

import akCounties from "./ak.json"
import alCounties from "./al.json"
import arCounties from "./ar.json"
import azCounties from "./az.json"
import caCounties from "./ca.json"
import coCounties from "./co.json"
import ctCounties from "./ct.json"
import deCounties from "./de.json"
import flCounties from "./fl.json"
import gaCounties from "./ga.json"
import hiCounties from "./hi.json"
import iaCounties from "./ia.json"
import idCounties from "./id.json"
import ilCounties from "./il.json"
import inCounties from "./in.json"
import ksCounties from "./ks.json"
import kyCounties from "./ky.json"
import laCounties from "./la.json"
import maCounties from "./ma.json"
import mdCounties from "./md.json"
import meCounties from "./me.json"
import miCounties from "./mi.json"
import mnCounties from "./mn.json"
import moCounties from "./mo.json"
import msCounties from "./ms.json"
import mtCounties from "./mt.json"
import ncCounties from "./nc.json"
import ndCounties from "./nd.json"
import neCounties from "./ne.json"
import nhCounties from "./nh.json"
import njCounties from "./nj.json"
import nmCounties from "./nm.json"
import nvCounties from "./nv.json"
import nyCounties from "./ny.json"
import ohCounties from "./oh.json"
import okCounties from "./ok.json"
import orCounties from "./or.json"
import paCounties from "./pa.json"
import riCounties from "./ri.json"
import scCounties from "./sc.json"
import sdCounties from "./sd.json"
import tnCounties from "./tn.json"
import txCounties from "./tx.json"
import utCounties from "./ut.json"
import vaCounties from "./va.json"
import vtCounties from "./vt.json"
import waCounties from "./wa.json"
import wiCounties from "./wi.json"
import wvCounties from "./wv.json"
import wyCounties from "./wy.json"

export const countiesByAbbr: Record<string, CountyDemographics[]> = {
  AK: akCounties,
  AL: alCounties,
  AR: arCounties,
  AZ: azCounties,
  CA: caCounties,
  CO: coCounties,
  CT: ctCounties,
  DE: deCounties,
  FL: flCounties,
  GA: gaCounties,
  HI: hiCounties,
  IA: iaCounties,
  ID: idCounties,
  IL: ilCounties,
  IN: inCounties,
  KS: ksCounties,
  KY: kyCounties,
  LA: laCounties,
  MA: maCounties,
  MD: mdCounties,
  ME: meCounties,
  MI: miCounties,
  MN: mnCounties,
  MO: moCounties,
  MS: msCounties,
  MT: mtCounties,
  NC: ncCounties,
  ND: ndCounties,
  NE: neCounties,
  NH: nhCounties,
  NJ: njCounties,
  NM: nmCounties,
  NV: nvCounties,
  NY: nyCounties,
  OH: ohCounties,
  OK: okCounties,
  OR: orCounties,
  PA: paCounties,
  RI: riCounties,
  SC: scCounties,
  SD: sdCounties,
  TN: tnCounties,
  TX: txCounties,
  UT: utCounties,
  VA: vaCounties,
  VT: vtCounties,
  WA: waCounties,
  WI: wiCounties,
  WV: wvCounties,
  WY: wyCounties,
}
